//
//  BiometricGate.swift
//
//  ⚠️ REQUIRED INFO.PLIST KEY — THE APP CRASHES WITHOUT IT ⚠️
//
//  Face ID cannot be used unless the app declares why it wants it. The first
//  time `evaluatePolicy` runs on a Face ID device with no declaration, the
//  system kills the process — not a thrown error, not a denial, a termination.
//
//  This project's Info.plist is generated by XcodeGen, so the key belongs in
//  `project.yml`, under the FirstApp target's existing `info.properties`:
//
//      info:
//        path: FirstApp/Info.plist
//        properties:
//          NSFaceIDUsageDescription: Unlock to view your saved API token.
//          # ...existing keys...
//
//  Touch ID needs no key. Only Face ID does — which is why this is so easy to
//  ship untested on a Touch ID device or the Simulator and discover in review.
//
//  The string is shown to the user in the system prompt, so it should name the
//  thing being protected, not the mechanism ("Unlock to view your saved API
//  token", not "This app uses Face ID").
//

import Foundation
import LocalAuthentication
import Observation

/// A lock over a screen or a piece of data, opened with Face ID, Touch ID, or
/// the device passcode.
///
/// ```swift
/// struct TokenView: View {
///     @Environment(\.scenePhase) private var scenePhase
///     @State private var gate = BiometricGate(reason: "Unlock to view your saved API token.")
///
///     var body: some View {
///         Group {
///             if gate.isUnlocked {
///                 TokenDetail()
///             } else {
///                 Button("Unlock") { Task { _ = await gate.authenticate() } }
///             }
///         }
///         .onChange(of: scenePhase) { _, phase in
///             if phase != .active { gate.lock() }
///         }
///     }
/// }
/// ```
///
/// - Important: This gates the **UI**, not the data. A biometric check is an
///   assertion by the OS about who is holding the device; it is not encryption,
///   and anything it protects is still readable by anyone with the file. Store
///   the secret in the Keychain with an access control that requires
///   authentication if it needs real protection — then the gate and the storage
///   agree instead of the gate being decorative.
@Observable
@MainActor
final class BiometricGate {

    /// Shown in the system prompt beneath "Face ID" / "Touch ID". Never logged.
    private let reason: String

    /// Whether authentication has succeeded and not since been revoked.
    ///
    /// Reset by ``lock()``. This is in-memory only and does not survive a
    /// process launch, which is the correct default for a lock.
    private(set) var isUnlocked: Bool = false

    /// Guards against a second prompt while one is on screen. A view whose
    /// `.task` runs twice, or an impatient double tap, would otherwise queue a
    /// second evaluation that the system rejects with `notInteractive`.
    /// Not observable: it is bookkeeping, not state a view should redraw for.
    @ObservationIgnored private var isAuthenticating: Bool = false

    /// - Parameter reason: Why the app is asking, phrased for the person
    ///   reading the prompt. Must not be empty — the system prompt renders a
    ///   blank line, and on some OS versions refuses to evaluate at all.
    init(reason: String) {
        self.reason = reason
    }

    // MARK: - Capability

    /// Which biometry this device offers: `.faceID`, `.touchID`, `.opticID`,
    /// or `.none`.
    ///
    /// Use it to label the unlock button correctly — see ``biometryName``.
    /// Asking someone to "use Touch ID" on a Face ID phone is a small thing
    /// that reads as a broken app.
    ///
    /// - Note: `LAContext.biometryType` is unset until a policy has been
    ///   evaluated against the context, which is why this queries
    ///   `canEvaluatePolicy` first. Reading the property on a fresh context
    ///   without that call returns `.none` on every device.
    var biometryType: LABiometryType {
        let context = LAContext()
        _ = context.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error: nil)
        return context.biometryType
    }

    /// The user-facing name of the available biometry, or `nil` when the device
    /// has none enrolled or usable. Passcode-only devices return `nil` here and
    /// still return `true` from ``isAvailable``.
    ///
    /// - Note: Anything a future OS adds falls through to `nil`, and the caller
    ///   shows generic "Unlock" wording rather than naming a modality it cannot
    ///   describe.
    var biometryName: String? {
        switch biometryType {
        case .faceID: return "Face ID"
        case .touchID: return "Touch ID"
        // Declared on iOS even though the hardware is not; omitting it makes
        // the switch non-exhaustive, which @unknown default does not cover
        // because that only absorbs cases added in a *future* SDK.
        case .opticID: return "Optic ID"
        case .none: return nil
        @unknown default: return nil
        }
    }

    /// Whether the device can authenticate its owner at all.
    ///
    /// Checked against ``LAPolicy/deviceOwnerAuthentication``, so this is `true`
    /// on a device with a passcode and no biometrics, and `false` only when no
    /// passcode is set. Gate the *presence* of a lock on this: offering to
    /// protect something on a device that cannot authenticate anyone produces a
    /// button that can never succeed.
    var isAvailable: Bool {
        LAContext().canEvaluatePolicy(.deviceOwnerAuthentication, error: nil)
    }

    // MARK: - Authentication

    /// Prompts for Face ID / Touch ID / passcode and, on success, sets
    /// ``isUnlocked``.
    ///
    /// - Returns: `.success` when the owner authenticated, otherwise the mapped
    ///   ``BiometricError``. Treat ``BiometricError/cancelled`` as a non-event:
    ///   the user closed the prompt on purpose and does not need an alert
    ///   telling them so.
    func authenticate() async -> Result<Void, BiometricError> {
        guard !isAuthenticating else { return .failure(.cancelled) }

        isAuthenticating = true
        defer { isAuthenticating = false }

        // A FRESH CONTEXT PER ATTEMPT, ALWAYS.
        //
        // `LAContext` caches its result for `touchIDAuthenticationAllowableReuseDuration`
        // and, more importantly, treats a context that has already evaluated
        // successfully as still-authenticated: calling `evaluatePolicy` on it
        // again returns success immediately, with no prompt and no biometric
        // check. Holding one context as a property therefore turns the second
        // and every subsequent unlock into a no-op that reports success — the
        // lock stays open for whoever picks the device up next. That is a real
        // security bug, and it is invisible in testing because the first unlock
        // behaves perfectly.
        let context = LAContext()

        // `.deviceOwnerAuthentication`, not `.deviceOwnerAuthenticationWithBiometrics`:
        // this policy falls back to the passcode when biometry fails or is
        // unavailable. The biometrics-only policy locks out a user with a
        // scarred fingerprint, a bandaged hand, a mask, a face that the sensor
        // stops recognising in low light, or five failed attempts — and locks
        // them out of their own data with no way back in the app.
        var policyError: NSError?
        guard context.canEvaluatePolicy(.deviceOwnerAuthentication, error: &policyError) else {
            return .failure(Self.map(policyError))
        }

        // Copied out so the completion handler captures a `String` rather than
        // the main-actor-isolated `self`.
        let localizedReason = reason

        let result: Result<Void, BiometricError> = await withCheckedContinuation { continuation in
            context.evaluatePolicy(.deviceOwnerAuthentication, localizedReason: localizedReason) { success, error in
                if success {
                    continuation.resume(returning: .success(()))
                } else {
                    continuation.resume(returning: .failure(Self.map(error)))
                }
            }
        }

        // Nothing is logged here, on any path. An authentication log is a
        // record of when a specific person was physically present at a device,
        // and the failure detail tells an attacker with console access which
        // factor to attack. Neither belongs in a log, a crash report, or an
        // analytics event.
        switch result {
        case .success:
            isUnlocked = true
        case .failure:
            // A failed attempt closes the gate rather than leaving a previous
            // success standing: a re-authentication that fails must not leave
            // the screen open behind it.
            isUnlocked = false
        }

        return result
    }

    /// Closes the gate.
    ///
    /// Callers are expected to call this when the app leaves the foreground,
    /// otherwise the unlocked screen is still on display in the app switcher
    /// and to whoever resumes the app next:
    ///
    /// ```swift
    /// .onChange(of: scenePhase) { _, phase in
    ///     if phase != .active { gate.lock() }
    /// }
    /// ```
    ///
    /// `!= .active` rather than `== .background` on purpose — `.inactive` is
    /// the phase during the app-switcher snapshot and while the control centre
    /// is pulled down, and that snapshot is what gets shown later.
    func lock() {
        isUnlocked = false
    }

    // MARK: - Error mapping

    /// Translates an `LAError` into the app's vocabulary.
    ///
    /// `nonisolated` so it can be called from the evaluation callback, which
    /// arrives on an arbitrary queue.
    private nonisolated static func map(_ error: Error?) -> BiometricError {
        guard let error else { return .failed("Authentication failed.") }

        guard let laError = error as? LAError else {
            return .failed(error.localizedDescription)
        }

        switch laError.code {
        case .userCancel, .appCancel, .systemCancel:
            // Three ways to arrive at "no one said no": the user dismissed it,
            // the app tore it down, the system pre-empted it with a call or a
            // lock. None is a failure and none should raise an alert.
            return .cancelled

        case .biometryNotEnrolled:
            return .notEnrolled

        case .biometryLockout:
            // Too many failed biometric attempts. Recoverable, but only by
            // entering the device passcode — which `.deviceOwnerAuthentication`
            // offers inside the same prompt, so a retry is worth offering.
            return .lockedOut

        case .passcodeNotSet:
            return .passcodeNotSet

        case .biometryNotAvailable:
            // Also what is returned when `NSFaceIDUsageDescription` is present
            // but the user has denied Face ID for this app in Settings.
            return .unavailable

        case .authenticationFailed:
            return .failed("Your identity could not be verified.")

        default:
            // `.userFallback`, `.invalidContext`, `.notInteractive`,
            // `.biometryDisconnected` and anything a future OS adds. The
            // localized description is the system's own generic wording; it
            // carries no detail about the attempt.
            return .failed(laError.localizedDescription)
        }
    }
}

// MARK: - Errors

/// Every way a biometric unlock can fail, flattened into one comparable value.
///
/// `Equatable` so a test can assert `XCTAssertEqual(error, .lockedOut)` rather
/// than pattern matching an opaque `Error`.
enum BiometricError: Error, Equatable, LocalizedError, Sendable {

    /// The device has no usable biometry, or the user has denied this app
    /// access to it in Settings.
    case unavailable

    /// The hardware is present but no face or fingerprint is enrolled.
    case notEnrolled

    /// Too many failed biometric attempts. The passcode still works.
    case lockedOut

    /// The user dismissed the prompt, or the system took it away. Not an error
    /// to report.
    case cancelled

    /// Anything else, carrying the system's own generic description.
    case failed(String)

    /// No device passcode is set, so the OS cannot authenticate anyone.
    case passcodeNotSet

    /// A sentence for the person using the app, not for the log.
    ///
    /// Each one names the thing the user can actually do; none of them names a
    /// policy, an `LAError` code, or how far the attempt got.
    var errorDescription: String? {
        switch self {
        case .unavailable:
            return "This device can't verify your identity right now. Check Face ID & Passcode in Settings."
        case .notEnrolled:
            return "No Face ID or Touch ID is set up on this device yet."
        case .lockedOut:
            return "Too many failed attempts. Enter your passcode to unlock."
        case .cancelled:
            return "Unlock was cancelled."
        case .failed(let description):
            return description
        case .passcodeNotSet:
            return "Set a passcode in Settings to protect this."
        }
    }

    /// Whether prompting again could plausibly succeed.
    ///
    /// ``lockedOut`` is retryable because `.deviceOwnerAuthentication` offers
    /// the passcode inside the same prompt. The three configuration failures
    /// are not — they need a trip to Settings first.
    var isRetryable: Bool {
        switch self {
        case .cancelled, .failed, .lockedOut:
            return true
        case .unavailable, .notEnrolled, .passcodeNotSet:
            return false
        }
    }
}
